export const HOUSES = [
  {
    name: 'Gryffindor',
    description: 'Brave, daring, and chivalrous',
    founder: 'Godric Gryffindor',
    animal: 'Lion',
    colorClass: 'bg-gryffindor-500',
    from: '--color-gryffindor-500',
    to: '--color-gryffindor-700',
    textColor: 'text-white',
  },
  {
    name: 'Slytherin',
    description: 'Ambitious, cunning, and resourceful',
    founder: 'Salazar Slytherin',
    animal: 'Serpent',
    colorClass: 'bg-slytherin-500',
    from: '--color-slytherin-500',
    to: '--color-slytherin-800',
    textColor: 'text-white',
  },
  {
    name: 'Hufflepuff',
    description: 'Loyal, patient, and hardworking',
    founder: 'Helga Hufflepuff',
    animal: 'Badger',
    colorClass: 'bg-hufflepuff-400',
    from: '--color-hufflepuff-400',
    to: '--color-hufflepuff-800',
    textColor: 'text-black',
  },
  {
    name: 'Ravenclaw',
    description: 'Intelligent, wise, and creative',
    founder: 'Rowena Ravenclaw',
    animal: 'Eagle',
    colorClass: 'bg-ravenclaw-500',
    from: '--color-ravenclaw-500',
    to: '--color-ravenclaw-800',
    textColor: 'text-white',
  },
] as const
